### ISSUE TITLE
Multiple src paths in :src -> none of them are built in the output-dir

### ISSUE THREAD

**Issue by gnl** [cljs/tool#17]
Here's my build config:

```
{:cljs-version "1.9.521"
 :dependencies []
 :builds       {:scripts {:src      ["src/scripts" "src/unit_scan/shared"]
                          :compiler {:main          "scripts.import-data"
                                     :output-to     "import-data.js"
                                     :output-dir    "target/scripts_out"
                                     :target        :nodejs
                                     :optimizations :none
                                     :source-map    true}}}}
```

I don't have time to look into this right now, but is it possible b/build here isn't too happy about being passed a vector?

https://github.com/cljs/tool/blob/9cf685d40261b8e6e1e067d0809d24c346c9d6b5/target/script/build.clj#L13

**Comment by shaunlebron** [comment]
sorry, I wasn't getting notifications from this org.

thanks! fixing now

**Comment by shaunlebron** [comment]
fixed: https://github.com/cljs/tool/commit/f976075349a8ca6724feff9e3951eee4873c5edd
