### ISSUE TITLE
dont require symbols in cljs.edn to be quoted

### ISSUE THREAD

**Issue by shaunlebron** [cljs/tool#26]
For some reason, symbols in [`:closure-defines`](http://cljs.github.io/api/compiler-options/closure-defines) have to be quoted in cljs.edn:

```clj
:closure-defines {'my.core/foo "bar"}
;                 ^ quote has to be here, but why?
```

**Comment by mikeball** [comment]
It would appear to be a feature of leiningen based on the note at this link, and best I can tell it's being done in the defproject macro, but not absolutely sure.

https://clojurescript.org/reference/compiler-options#closure-defines
https://github.com/technomancy/leiningen/pull/1456#r9932536
https://github.com/technomancy/leiningen/blob/80e649329a7aebca0efeb223d20649f474a07c31/leiningen-core/src/leiningen/core/project.clj#L422

Are you sure we want to go down the path of non-standard edn? My preference would be to just set a string key.

```clojure
:closure-defines {"my.core/foo" "bar"}
```

**Comment by shaunlebron** [comment]
I'm sorry, I meant in the context of this tool—why does our tool not work without the quote in above example in cljs.edn?

Not sure what you mean by non-standard edn, but if you check the "Details" section of http://cljs.github.io/api/compiler-options/closure-defines, you'll see that strings and symbols are interpreted differently, so we have to support both.

**Comment by mikeball** [comment]
This was just my initial research and the impression I got from the clojurescript.org doc page was that string/quoted keys were required, but in leiningen's project.clj everything is wrapped in the defproject macro, which does the implicit quoting. The non-standard edn would be something like the defproject macro wrapping the edn.

I will look into what we can do after the edn is loaded to make this work.

**Comment by shaunlebron** [comment]
fixed: https://github.com/cljs/tool/pull/34
