### ISSUE TITLE
bootstrapped script execution/repl mode

### ISSUE THREAD

**Issue by shaunlebron** [cljs/tool#6]
I basically want Planck for node.  Mike has done some work on this here: https://github.com/mfikes/elbow

Nasser has done some work with this here:
https://github.com/nasser/clojurescript-npm

**Comment by shaunlebron** [comment]
I think we can just pull in `lumo` as a dependency and run it as a default task for a quick repl.

Also, if passed a filename, execute with lumo.

**Comment by shaunlebron** [comment]
fixed 0c930e393d318453adbee55d38c195978adfd66f

**Comment by jiyinyiyong** [comment]
My current solution:

```bash
env=x lumo -i y.cljs
```

**Comment by shaunlebron** [comment]
@jiyinyiyong can you elaborate?

**Comment by jiyinyiyong** [comment]
I'm trying to use Lumo to my build scripts too, mostly generating HTML, there's a problem that Lumo  handles params in a way different from Node.js . I mean the params does not go to `process.argv` naturally, which is described at https://github.com/anmonteiro/lumo/issues/68 . Maybe you can have a solution here.

So I tried to use `env=x` to config the process and read configs from `process.env.env` to decide what to do. Meanwhile I keep multiple scripts for different tasks.

**Comment by shaunlebron** [comment]
Your env var trick works.  I couldn't get `*command-line-args*` to work, will file an issue.
