### ISSUE TITLE
allow dependencies in lumo

### ISSUE THREAD

**Issue by shaunlebron** [cljs/tool#8]
From `lumo --help`:

```
    -c cp, --classpath cp        Use colon-delimited cp for source
                                 directories and JARs
```

We can use existing dependency keys from cljs.edn.  Do auto-install before running lumo.

**Comment by jiyinyiyong** [comment]
Do you know any method to generate the dependencies very quickly? By now I'm using Boot and it slows me down every time I update the dependencies:

```bash
export boot_deps=`boot show -c`
lumo -Kc $boot_deps:src/ -i tasks/server.cljs
```

**Comment by shaunlebron** [comment]
Just cache the classpath to a file, and only update it when you want.

**Comment by shaunlebron** [comment]
fixed: 0baa4fbc2669cb435de56c523fe1c21171079f8d

**Comment by jiyinyiyong** [comment]
I tried as you said. I got a feedback that the path I cached contains `/Users/chen/...` which is my username on my own Mac.

Have you found a better way to manage deps in Lumo now?

**Comment by shaunlebron** [comment]
not sure I understand what happened. some ideas:

- use the caching example here: http://planck-repl.org/dependencies.html
- try out calvin? https://github.com/eginez/calvin

**Comment by jiyinyiyong** [comment]
My file.. https://github.com/mvc-works/stack-workflow/blob/master/tasks/class-path.sh

**Comment by shaunlebron** [comment]
maybe you can file an issue and attach a minimal working example.  i'm still not sure what the problem is

**Comment by jiyinyiyong** [comment]
I know the problem in my solution. I saved the classpath in in repo and it does not match the file system of others. I guess waiting calvin to become mature is my best choice.
